Settings:
  CommandSound:
    success:
      sound: ORB_PICKUP
    error:
      sound: ORB_PICKUP
  # Enable plugin's functionality?
  enableConfirmation: true
  # The currency symbol
  currencySymbol: '$'
  # The plugin prefix
  prefix: '&7[ &bConfirmation &7]&f '
  # Should we enable the log file?
  enableLogFile: true
  # Transaction type translation, also support for special character and color
  transactionType:
    BUY: 'Buy'
    SELL: 'Sell'
  # The price format. This will format the price from 1000 to 1k!
  PriceFormat:
    enable: true # Please be aware that the number will not be 100% precise!. For example 125.6 will not always be 125.6. It could change to 125!
    THOUSANDS: 'k'
    MILLIONS: 'M'
    BILLIONS: 'B'
    TRILLIONS: 'T'
# Available key :
    #  material > Material as string (String)
    #   example > DIRT
    #  itemID > The durability or item ID , useful for custom item texture or specifying item type(int)
    #   example > 5
    #  amount > The item amount (int)
    #   example > 5
    #  name > The item displayName (String)
    #   example > '&7[ &bHello World &7]'
    #  lore > The item lore (List String)
    #   example > - 'Hello'
    #             - 'World'
    #  glow > Set the item glow or not (bool)
    #   example > true or false
    #  texture > The head texture url (String)
    #   example > http://textures.minecraft.net/texture/d67470a0c18f6851e914353719e795877d29b3252f7e6bd4a1b865765bd74feb
    # For material list you can find it here https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Material.html
  # The confirmation will only open if this requirement are met
  # Syntax : <world, all>:<BUY, SELL, BOTH, DISABLED>
  ConfirmationOpenRule:
    - 'all:BOTH' # Will open on every world for both transaction type, its recommended to keep this one here
    - 'world:BUY' # Will only open in world = world and when the transaction type is BUY. This will override the 'all'
Inventory:
  Confirmation:
    # Sound list can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    clickSound:
      sound: CLICK
    openSound:
      sound: CHEST_OPEN
    closeSound:
      sound: CHEST_CLOSE
    title: 'Confirmation'
    FillEmpty:
      # Should we fill it?
      should: true
      # The item. Format is same as above
      item:
        material: STAINED_GLASS_PANE
        itemID: 7
        name: '.'
    enablePreview: true
    AcceptButton:
      slot: 10
      material: WOOL
      itemID: 5
      name: '&a&lCONFIRM &7(Click&7)'
      lore:
        - '&8&m+--------------------+'
        - '&r'
        - '&7(&b✿&7) &8» &fClick to &e%transaction_type%'
    DeclineButton:
      slot: 16
      material: WOOL
      itemID: 14
      name: '&c&lCANCEL &7(Click&7)'
      lore:
        - '&8&m+--------------------+'
        - '&r'
        - '&7(&b✿&7) &8» &fClick to close'
    ItemPreviewButton:
      slot: 13
      material: DIRT # Don't worry, this will change. Depending on what item is inside
      name: '&7[&e%transaction_type%&7] &8» &f%item_name%' # This will rename the item display preview. You can use %item_name% to use the default item name / display name
      lore:
        - '&8&m+--------------------+'
        - '&r'
        - ' &b✿ &fOwner &8» &e%shop_owner%'
        - ' &b✿ &f%transaction_type% Price &8» &e%currency_symbol%%price%'
        - ' &b✿ &fItem &8» &e%item% &7(x%item_amount%&7)'
        - '&r'
        - '&8&m+--------------------+'
        - '&r'
        - '&b✿ &fItem Lore &8»'
        - '%item_lore%' # You can remove this if you want to
  Information:
    title: 'Information'
    # Sound list can be found at https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
    clickSound:
      sound: CLICK
    openSound:
      sound: CHEST_OPEN
    closeSound:
      sound: CHEST_CLOSE
    FillEmpty:
      # Should we fill it?
      should: true
      # The item. Format is same as above
      item:
        material: STAINED_GLASS_PANE
        itemID: 7
        name: '.'
    InformationButton:
      material: PAPER
      slot: 13
      name: '&7[ &bInfo &7]'
      lore:
        - '&8&m+--------------------+'
        - '&r'
        - '&7(&e%transaction_type%-ing &7item is disabled on this shop&7)'
Messages:
  cant-open-chest: '&fCan''t do that right now..'
  confirmation-world-disabled: '&fShop confirmation for shop type &e%shopType &fare disabled in this world'
  command:
    no-permission: 'You don''t have the right permission to run this command!'
    invalid-arg: 'Invalid command!'
    config-reloaded: 'Config has been reloaded!'
    confirmation-disabled: '&eConfirmation &fhas been &cdisabled &fglobally!'
    confirmation-enabled: '&eConfirmation &fhas been &aenabled &fglobally!'
