name: ChestShopConfirmation
version: @version@
main: me.droreo002.chestshopconfirmation.ChestShopConfirmation
depend: [ChestShop, OreoCore]

commands:
  chestshopconfirmation:
    aliases:
      - csc
